import type { NextPage } from 'next'
import Head from 'next/head'
import { useSiteContext } from '../context/state'

//component imports
import Settings from '../components/settings/settings'
import Titlecard from '../components/titlecard/titlecard'

//styling and soforth
import cn from 'classnames'
import styles from '../styles/Home.module.scss'



const Home: NextPage = () => {

  return (
    <div className={cn({
      [styles.container]: true
    })}>
      <Head>
        <title>Jackson Tarlin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <Settings />
      </header>
      <main className={styles.main}>
        <Titlecard />
      </main>

      <footer>
      </footer>
    </div>
  )
}

export default Home
